# Day 1

In [1]:
import pandas as pd
day_1_input = pd.read_csv("day_1_input",header=None)
day_1_input.columns = ['depth']
print(day_1_input)

depth = day_1_input['depth']

      depth
0       178
1       205
2       212
3       210
4       215
...     ...
1995   8734
1996   8741
1997   8750
1998   8753
1999   8755

[2000 rows x 1 columns]


## Part 1

In [2]:
test_1_1 = [x < y for x, y in zip(depth,depth[1:])]
print(test_1_1.count(True))

1676


## Part 2

In [3]:
sliding_window = [x + y +z for x, y, z in zip(depth,depth[1:],depth[2:])]

print(sliding_window)

test_1_2 = [x < y for x, y in zip(sliding_window,sliding_window[1:])]

print(test_1_2)

[595, 627, 637, 645, 658, 667, 677, 686, 697, 692, 686, 678, 691, 713, 735, 748, 752, 764, 786, 817, 840, 853, 866, 879, 896, 917, 940, 970, 1023, 1042, 1051, 1026, 1012, 993, 982, 982, 985, 978, 986, 989, 999, 1006, 1040, 1056, 1057, 1038, 1030, 1053, 1065, 1077, 1068, 1069, 1070, 1075, 1090, 1105, 1122, 1129, 1110, 1082, 1058, 1060, 1072, 1080, 1090, 1100, 1091, 1081, 1060, 1066, 1087, 1106, 1119, 1118, 1124, 1127, 1111, 1098, 1100, 1121, 1158, 1185, 1232, 1263, 1293, 1323, 1352, 1382, 1390, 1419, 1453, 1496, 1522, 1547, 1569, 1607, 1636, 1662, 1699, 1757, 1828, 1872, 1896, 1907, 1915, 1923, 1929, 1935, 1941, 1947, 1956, 1959, 1965, 1964, 1970, 1977, 1987, 2000, 2017, 2045, 2079, 2106, 2117, 2112, 2106, 2105, 2110, 2114, 2120, 2136, 2156, 2171, 2177, 2185, 2196, 2207, 2212, 2236, 2259, 2283, 2290, 2298, 2303, 2316, 2329, 2347, 2355, 2382, 2416, 2450, 2463, 2466, 2476, 2489, 2508, 2520, 2534, 2543, 2552, 2559, 2560, 2564, 2565, 2572, 2587, 2605, 2596, 2590, 2590, 2635, 2672, 2700, 271

In [4]:
print(test_1_2.count(True))

1706


# Day 2 - Dive

## Part 1

In [7]:
day_2_input = pd.read_csv("day_2_input.txt",header=None, sep = " ")
day_2_input.columns = ['dir','dist']

instructions = day_2_input
print(instructions)

         dir  dist
0    forward     8
1    forward     1
2       down     9
3       down     8
4       down     5
..       ...   ...
995  forward     6
996  forward     1
997  forward     2
998       up     5
999  forward     9

[1000 rows x 2 columns]


In [10]:
totals = instructions.groupby(['dir']).sum()
print(totals)

         dist
dir          
down     1927
forward  2018
up       1107


In [13]:
day_2_final_value = (totals['dist']['down'] - totals['dist']['up'])*totals['dist']['forward']
print(day_2_final_value)

1654760


## Part 2

In [21]:
aim = 0
pos = 0
depth = 0
for i, inst in instructions.iterrows():
    if inst['dir'] == 'down':
        aim+= inst['dist']
    elif inst['dir'] == 'up':
        aim-= inst['dist']
    elif inst['dir'] == 'forward':
        pos += inst['dist']
        depth += aim * inst['dist']
        
print(aim,pos,depth)

print(pos*depth)


820 2018 969300
1956047400


# Day 3

## Part 1

In [31]:
day_3_input = pd.read_csv("day_3_input.txt",header=None, dtype=str)
print(day_3_input[0])



0      001111011011
1      000110001010
2      011010111111
3      010011001110
4      011001101000
           ...     
995    100110010011
996    111010110000
997    110111010000
998    100010011110
999    110011100110
Name: 0, Length: 1000, dtype: object


In [32]:
df = day_3_input[0].apply(lambda x: pd.Series(list(x)))
print(df)

     0  1  2  3  4  5  6  7  8  9 10 11
0    0  0  1  1  1  1  0  1  1  0  1  1
1    0  0  0  1  1  0  0  0  1  0  1  0
2    0  1  1  0  1  0  1  1  1  1  1  1
3    0  1  0  0  1  1  0  0  1  1  1  0
4    0  1  1  0  0  1  1  0  1  0  0  0
..  .. .. .. .. .. .. .. .. .. .. .. ..
995  1  0  0  1  1  0  0  1  0  0  1  1
996  1  1  1  0  1  0  1  1  0  0  0  0
997  1  1  0  1  1  1  0  1  0  0  0  0
998  1  0  0  0  1  0  0  1  1  1  1  0
999  1  1  0  0  1  1  1  0  0  1  1  0

[1000 rows x 12 columns]


In [50]:
df = df.apply(pd.to_numeric, errors='coerce', downcast='signed')
gamma_totals = df.sum(axis=0) > 500
print(gamma_totals.astype(int))

0     0
1     0
2     0
3     1
4     1
5     0
6     1
7     0
8     0
9     0
10    1
11    1
dtype: int64


In [51]:
gamma_bin = gamma_totals.astype(int).astype(str).str.cat(sep='')
print(gamma_bin)
gamma = int(gamma_bin,2)
print(gamma)

000110100011
419


In [52]:
epsilon_totals = df.sum(axis=0) < 500
print(epsilon_totals.astype(int))
epsilon_bin = epsilon_totals.astype(int).astype(str).str.cat(sep='')
print(epsilon_bin)
epsilon = int(epsilon_bin,2)
print(epsilon)

0     1
1     1
2     1
3     0
4     0
5     1
6     0
7     1
8     1
9     1
10    0
11    0
dtype: int64
111001011100
3676


In [53]:
print(gamma * epsilon)

1540244


## Part 2

In [96]:
search_df = df

for i in range(0,12):
    test_bit = search_df.sum(axis=0) >= len(search_df)/2
    search_df = search_df[df.iloc[:, int(i)] == int(test_bit[i])]
    if len(search_df) <= 1:
        break

ox_gen_bin = search_df.iloc[0].astype(str).str.cat(sep='')
print(ox_gen_bin)
ox_gen = int(ox_gen_bin,2)
print(ox_gen)


     0  1  2  3  4  5  6  7  8  9  10  11
0    0  0  1  1  1  1  0  1  1  0   1   1
1    0  0  0  1  1  0  0  0  1  0   1   0
2    0  1  1  0  1  0  1  1  1  1   1   1
3    0  1  0  0  1  1  0  0  1  1   1   0
4    0  1  1  0  0  1  1  0  1  0   0   0
..  .. .. .. .. .. .. .. .. .. ..  ..  ..
995  1  0  0  1  1  0  0  1  0  0   1   1
996  1  1  1  0  1  0  1  1  0  0   0   0
997  1  1  0  1  1  1  0  1  0  0   0   0
998  1  0  0  0  1  0  0  1  1  1   1   0
999  1  1  0  0  1  1  1  0  0  1   1   0

[1000 rows x 12 columns]
False
     0  1  2  3  4  5  6  7  8  9  10  11
0    0  0  1  1  1  1  0  1  1  0   1   1
1    0  0  0  1  1  0  0  0  1  0   1   0
2    0  1  1  0  1  0  1  1  1  1   1   1
3    0  1  0  0  1  1  0  0  1  1   1   0
4    0  1  1  0  0  1  1  0  1  0   0   0
..  .. .. .. .. .. .. .. .. .. ..  ..  ..
981  0  0  1  1  1  0  1  1  1  0   1   1
987  0  0  0  0  0  1  1  0  0  0   1   0
988  0  0  0  1  0  1  1  0  0  0   0   0
990  0  1  1  0  0  0  0  1  1  0   1   0
99

<ipython-input-96-1a4c809658d6>:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  search_df = search_df[df.iloc[:, int(i)] == int(test_bit[i])]
<ipython-input-96-1a4c809658d6>:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  search_df = search_df[df.iloc[:, int(i)] == int(test_bit[i])]
<ipython-input-96-1a4c809658d6>:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  search_df = search_df[df.iloc[:, int(i)] == int(test_bit[i])]
<ipython-input-96-1a4c809658d6>:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  search_df = search_df[df.iloc[:, int(i)] == int(test_bit[i])]
<ipython-input-96-1a4c809658d6>:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  search_df = search_df[df.iloc[:, int(i)] == int(test_bit[i])]
<ipython-input-96-1a4c809658d6>:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  search_df = 

In [97]:
search_df = df

for i in range(0,12):
    test_bit = search_df.sum(axis=0) < len(search_df)/2
    search_df = search_df[df.iloc[:, int(i)] == int(test_bit[i])]
    if len(search_df) <= 1:
        break

co2_bin = search_df.iloc[0].astype(str).str.cat(sep='')
print(co2_bin)
co2 = int(co2_bin,2)
print(co2)
print(ox_gen * co2)

     0  1  2  3  4  5  6  7  8  9  10  11
0    0  0  1  1  1  1  0  1  1  0   1   1
1    0  0  0  1  1  0  0  0  1  0   1   0
2    0  1  1  0  1  0  1  1  1  1   1   1
3    0  1  0  0  1  1  0  0  1  1   1   0
4    0  1  1  0  0  1  1  0  1  0   0   0
..  .. .. .. .. .. .. .. .. .. ..  ..  ..
995  1  0  0  1  1  0  0  1  0  0   1   1
996  1  1  1  0  1  0  1  1  0  0   0   0
997  1  1  0  1  1  1  0  1  0  0   0   0
998  1  0  0  0  1  0  0  1  1  1   1   0
999  1  1  0  0  1  1  1  0  0  1   1   0

[1000 rows x 12 columns]
True
     0  1  2  3  4  5  6  7  8  9  10  11
6    1  0  0  0  0  1  0  0  0  0   1   1
7    1  0  0  1  0  0  0  0  1  1   0   1
9    1  0  1  0  0  1  0  1  0  0   1   0
10   1  1  0  1  0  0  0  0  1  0   0   1
14   1  0  0  0  0  0  0  0  0  0   0   0
..  .. .. .. .. .. .. .. .. .. ..  ..  ..
995  1  0  0  1  1  0  0  1  0  0   1   1
996  1  1  1  0  1  0  1  1  0  0   0   0
997  1  1  0  1  1  1  0  1  0  0   0   0
998  1  0  0  0  1  0  0  1  1  1   1   0
999

<ipython-input-97-7ee1c04ff772>:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  search_df = search_df[df.iloc[:, int(i)] == int(test_bit[i])]
<ipython-input-97-7ee1c04ff772>:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  search_df = search_df[df.iloc[:, int(i)] == int(test_bit[i])]
<ipython-input-97-7ee1c04ff772>:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  search_df = search_df[df.iloc[:, int(i)] == int(test_bit[i])]
<ipython-input-97-7ee1c04ff772>:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  search_df = search_df[df.iloc[:, int(i)] == int(test_bit[i])]
<ipython-input-97-7ee1c04ff772>:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  search_df = search_df[df.iloc[:, int(i)] == int(test_bit[i])]
<ipython-input-97-7ee1c04ff772>:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  search_df = 

# Day 4

## Part 1

In [184]:
import numpy as np 

def test_bingo_board(df, numbers):
    res = False
    for i, row in df.iterrows():
        res = res or test_bingo_row(row,numbers)
    for i, col in df.transpose().iterrows():
        res = res or test_bingo_row(col,numbers)
    return res
    
def test_bingo_row(row, numbers):
    test = row.isin(numbers)
    res = test.all()
    return res


def score_bingo_board(df, numbers):
    flat = df.unstack().reset_index(drop=True)
    test = np.logical_not(flat.isin(numbers))

    sum_remaining = flat[test].sum()
    return sum_remaining * numbers[-1:]


board_df = pd.DataFrame(np.array([[22, 13, 17, 11,  0], [8, 2, 23,  4, 24], [21,  9, 14, 16,  7],[6, 10,  3, 18, 5],  [1, 12, 20, 15, 19]]))

print(test_bingo_board(board_df,pd.Series([17, 23, 2, 0, 4, 21, 24, 8])))
print(score_bingo_board(board_df,pd.Series([17, 23, 2, 0, 4, 21, 24, 8])))
print(test_bingo_board(board_df,pd.Series([17, 23, 2, 0, 543, 21, 24, 8])))




True
7    1608
dtype: int64
False


In [189]:
from io import StringIO
import re

lines = tuple(open('day_4_input.txt', 'r'))

numbers = lines[0]

lines = [line for line in lines[2:] if not line == '\n']

boards = ["".join(lines[i:i + 5]) for i in range(0, len(lines), 5)]

boards_parsed = [pd.read_csv(StringIO(board), header=None, sep='\s+') for board in boards]
    
#print(boards_parsed)

numbers_parsed = pd.read_csv(StringIO(numbers), header=None, sep=',').transpose()[0]
print(numbers_parsed)



0     17
1      2
2     33
3     86
4     38
      ..
95    87
96    97
97    32
98    39
99    82
Name: 0, Length: 100, dtype: int64


In [190]:
for i in range(5,100):
    for board in boards_parsed:
        bingo = test_bingo_board(board,numbers_parsed[:i])
        if bingo:
            print(board)
            print(i)
            print(numbers_parsed[:i])
            print(score_bingo_board(board,numbers_parsed[:i]))
            break
    if bingo:
        break
    

    0   1   2   3   4
0  73  41  26  87  95
1  62  99  58   9  20
2  45  10  71  28  39
3  89  17  29  46  81
4  49  35  24  74  32
21
0     17
1      2
2     33
3     86
4     38
5     41
6      4
7     34
8     91
9     61
10    11
11    81
12     3
13    59
14    29
15    71
16    26
17    44
18    54
19    89
20    46
Name: 0, dtype: int64
20    38594
Name: 0, dtype: int64


In [205]:
bs_to_ignore = list()

for i in range(5,len(numbers_parsed)+1):
        
    for b, board in enumerate(boards_parsed):
        if b in bs_to_ignore:
            continue
        bingo = test_bingo_board(board,numbers_parsed[:i])
        if bingo:
            #print(board)
            #print(i)
            #print(numbers_parsed[:i])
            #print(score_bingo_board(board,numbers_parsed[:i]))
            bs_to_ignore.append(b)
            board_to_ignore = board
            #break



In [206]:
print(bs_to_ignore)
print(board_to_ignore)

for i in range(5,len(numbers_parsed)+1):
    bingo = test_bingo_board(board_to_ignore,numbers_parsed[:i])
    if bingo:
        print(numbers_parsed[:i])
        print(score_bingo_board(board_to_ignore,numbers_parsed[:i]))
        break

[22, 49, 18, 2, 17, 99, 81, 94, 20, 5, 93, 70, 88, 25, 66, 4, 11, 15, 45, 90, 40, 58, 98, 77, 21, 26, 29, 50, 56, 53, 41, 92, 1, 47, 69, 78, 91, 95, 28, 60, 61, 9, 57, 86, 33, 3, 6, 51, 19, 68, 79, 31, 55, 71, 12, 32, 34, 44, 63, 72, 74, 87, 35, 24, 0, 38, 97, 23, 42, 37, 84, 85, 89, 80, 96, 27, 59, 82, 7, 13, 64, 76, 8, 10, 16, 48, 73, 62, 65, 30, 75, 52, 46, 83, 14, 36, 67, 39, 54, 43]
    0   1   2   3   4
0  86  89  64  69  76
1  53  82  24  16  51
2  67  75   3  33  21
3  23  63  99  13  43
4   4  39   7  73  87
0     17
1      2
2     33
3     86
4     38
      ..
81    72
82    60
83    16
84    12
85    64
Name: 0, Length: 86, dtype: int64
85    21184
Name: 0, dtype: int64


# Day 5
##Part 1

In [5]:
import re
import pandas as pd
import numpy as np

lines = tuple(open('day_5_input.txt', 'r'))

#print(lines)

rows = list()


for i, line in enumerate(lines):
    matches = re.search('(\d+),(\d+) -> (\d+),(\d+)',line)
    x1 = int(matches.group(1))
    y1 = int(matches.group(2))
    x2 = int(matches.group(3))
    y2 = int(matches.group(4))
    rows.append(np.array([x1,y1,x2,y2]))

    
df = pd.DataFrame(rows, columns = ['x1','y1','x2','y2'])

print(df)


      x1   y1   x2   y2
0    503  977  843  637
1    437  518  437  225
2    269  250  625  250
3    846  751  646  751
4     18  731  402  731
..   ...  ...  ...  ...
495  657  232  657  945
496  518  392  518  621
497  268  959  896  331
498  886  616  841  616
499  375  503  375  387

[500 rows x 4 columns]


In [23]:
max_value = int(df.max().max())
max_value = 1000
vent_lines = np.zeros((max_value+1,max_value+1))

#print(vent_lines)

for i, row in df.iterrows():

    x_min = min(row['x1'],row['x2'])
    x_max = max(row['x1'],row['x2'])
    x_range = range(x_min,x_max+1)

    y_min = min(row['y1'],row['y2'])
    y_max = max(row['y1'],row['y2'])
    y_range = range(y_min,y_max+1)
    
    if x_min == x_max or y_min == y_max:
        for x in x_range:
            for y in y_range:
                vent_lines[x][y] = vent_lines[x][y]+1
    else:
        ## PART 2
        for i, x in enumerate(x_range):
            vent_lines[x][y_range[i]] = vent_lines[x][y_range[i]]+1

        


            #print("{} {}: {}".format(x,y,vent_lines[x][y]))

print(vent_lines)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [24]:
# 957854 too high
# 953149 too high
# 199 too low

print(vent_lines)

unique, counts = np.unique(vent_lines > 1, return_counts=True)
dict(zip(unique, counts))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


{False: 981235, True: 20766}

In [ ]:
## Part 2

In [40]:
# 20766 too high

max_value = int(df.max().max())
max_value = 1000
vent_lines = np.zeros((max_value+1,max_value+1))

#print(vent_lines)

for idx, row in df.iterrows():

    x_min = min(row['x1'],row['x2'])
    x_max = max(row['x1'],row['x2'])
    
    if row['x1'] > row['x2']:
        x_range = [x for x in reversed(range(x_min,x_max+1))]
    else:
        x_range = range(x_min,x_max+1)


    y_min = min(row['y1'],row['y2'])
    y_max = max(row['y1'],row['y2'])
    
    if row['y1'] > row['y2']:
        y_range = [y for y in reversed(range(y_min,y_max+1))]
    else:
        y_range = range(y_min,y_max+1)

        
    if x_min == x_max or y_min == y_max:
        for x in x_range:
            for y in y_range:
                vent_lines[x][y] = vent_lines[x][y]+1
    else:
        #print(row)
        #print(x_range)
        #print(y_range)
        for i, x in enumerate(x_range):
            vent_lines[x][y_range[i]] = vent_lines[x][y_range[i]]+1
            #print("{},{}".format(x,y_range[i]))
        #break

        
print(vent_lines)

unique, counts = np.unique(vent_lines > 1, return_counts=True)
dict(zip(unique, counts))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


{False: 982230, True: 19771}

In [ ]:
#Day 6
## Part1

In [58]:
fishies = pd.read_csv('day_6_input.txt', header=None).transpose()
fishies.columns = ['num']

print(fishies)

fishies_s = fishies['num']

for i in range(0,80):
    fishies_s = fishies_s - 1
    count = fishies_s[fishies_s== -1].count()
    fishies_s[fishies_s== -1] = 6
    new_fishies = pd.Series(np.ones(count)*8)
    fishies_s = fishies_s.append(new_fishies)
    
#    print(new_fishies)

print(fishies_s)

     num
0      2
1      1
2      1
3      1
4      1
..   ...
295    1
296    1
297    2
298    1
299    1

[300 rows x 1 columns]
0        6.0
1        5.0
2        5.0
3        5.0
4        5.0
        ... 
49051    8.0
49052    8.0
49053    8.0
49054    8.0
49055    8.0
Length: 388739, dtype: float64


In [85]:
fishies = pd.read_csv('day_6_input.txt', header=None).transpose()
fishies.columns = ['num']


fish_counts = fishies['num'].value_counts()
fish_counts = fish_counts.append(pd.Series({0:0,6:0,7:0,8:0}))
fish_counts.sort_index(inplace=True)
print(fish_counts)


for i in range(0,256):
    reset_fish = fish_counts[0]
    fish_counts = fish_counts.shift(-1)
    fish_counts[6] = fish_counts[6] + reset_fish
    fish_counts[8] = reset_fish

print(fish_counts.sum())

0      0
1    200
2     27
3     25
4     23
5     25
6      0
7      0
8      0
dtype: int64
1741362314973.0


In [ ]:
#Day 7
##Part 1

In [95]:
crabs = pd.read_csv('day_7_input.txt', header=None).transpose()[0]
print(crabs)

0      1101
1         1
2        29
3        67
4      1102
       ... 
995     274
996      72
997     628
998    1119
999     195
Name: 0, Length: 1000, dtype: int64


In [99]:
costs = dict()
#print(min(crabs))
for p in range(min(crabs),max(crabs)):
    costs[p] = sum([abs(x-p) for x in crabs])
    
#print(costs)

key = min(costs, key=costs.get)
print(key, costs[key])

363 341534


In [ ]:
## Part 2

In [105]:
# 93044017.0 too low

costs = dict()
#print(min(crabs))
for p in range(min(crabs),max(crabs)):
    #print(p)
    #print(crabs)
    #print([abs(x-p)*(abs(x-p)+1)/2 for x in crabs])
    costs[p] = sum([abs(x-p)*(abs(x-p)+1)/2 for x in crabs])
    
#print(costs)

key = min(costs, key=costs.get)
print(key, costs[key])

484 93397632.0


In [106]:
# Day 8 

In [107]:
## Part 1

In [123]:
lines = tuple(open('day_8_input.txt', 'r'))

line = lines[0]

count_appearances = pd.Series(np.zeros(10))
count_appearances.index = count_appearances.index + 1

for line in lines:
    split = line.split('|')
    digits = split[0].strip().split(" ")
    display = split[1].strip().split(" ")
    #print(digits)
    #print(display)

    for d in display:
        if len(d) == 2:
            #it's a 1
            count_appearances[1] = count_appearances[1] + 1
        elif len(d) == 4:
            #it's a 4
            count_appearances[4] = count_appearances[4] + 1
        elif len(d) == 3:
            #it's a 7
            count_appearances[7] = count_appearances[7] + 1
        elif len(d) == 7:
            #it's an 8
            count_appearances[8] = count_appearances[8] + 1

print(count_appearances)
print(count_appearances.sum())

1     98.0
2      0.0
3      0.0
4     83.0
5      0.0
6      0.0
7     89.0
8     95.0
9      0.0
10     0.0
dtype: float64
365.0


In [182]:
output_display = list()

for line in lines:
    split = line.split('|')
    digits = split[0].strip().split(" ")
    display = split[1].strip().split(" ")

    # a is in 7 (len=3) but not 1 (len=2)
    # b is in six digits
    # e is in four digits
    # f is in nine digits
    
    # c is in 7 but isn't a or f.
    # d is in 4 but isn't b,c or f.
    # g is what's left.
    
    # only digit missing f is 2

    mappings = dict()
    
    one = [d for d in digits if len(d) == 2][0]
    four = [d for d in digits if len(d) == 4][0]
    seven = [d for d in digits if len(d) == 3][0]
    eight = [d for d in digits if len(d) == 7][0]
    
    mappings['a'] = (set(seven) - set(one)).pop()
    
    counts = {[c in d for d in digits].count(True):c for c in 'abcdefg'}
    mappings['b'] = counts[6]
    mappings['e'] = counts[4]
    mappings['f'] = counts[9]
    
    mappings['c'] = (set(seven) - set(mappings['a']+ mappings['f'])).pop()
    mappings['d'] = (set(four) - set(mappings['b']+mappings['c']+ mappings['f'])).pop()
    
    mappings['g'] = (set('abcdefg') - set(mappings.values())).pop()
        
    inv_map = {v: k for k, v in mappings.items()}


    seven_disp_map = {'abcdefg': 8,
        'abdfg': 5,
        'acdeg': 2,
        'acdfg': 3,
        'acf': 7,
        'abcdfg': 9,
        'abdefg': 6,
        'bcdf': 4,
        'abcefg': 0,
        'cf': 1}
        
    digits_mapped = [''.join(sorted([inv_map.get(i, i) for i in d])) for d in display]
    
    output_display.append(int("".join([str(seven_disp_map[d]) for d in digits_mapped])))
        

print(output_display)
print(sum(output_display))


[7894, 8202, 5873, 2188, 2790, 5362, 8821, 8357, 2660, 2562, 2277, 4690, 8018, 2370, 8127, 969, 3977, 8454, 7937, 4236, 5954, 4486, 3992, 2717, 1462, 2807, 6145, 2078, 933, 141, 8988, 3622, 9888, 8486, 1768, 6837, 2727, 6815, 7008, 4158, 1117, 2147, 4675, 9216, 3932, 4142, 1594, 465, 8161, 2362, 3905, 7125, 1888, 686, 2058, 4905, 4778, 4930, 1532, 5759, 4445, 7781, 7476, 1949, 5455, 7815, 1243, 7126, 6210, 8185, 4912, 7260, 7693, 7079, 4216, 2439, 1152, 5183, 834, 5431, 1611, 4885, 4119, 4402, 9091, 3519, 1853, 3968, 7954, 1706, 8457, 6774, 6550, 3618, 1964, 821, 2201, 7843, 8710, 5494, 3638, 4655, 4475, 4835, 3646, 2571, 8689, 9535, 6602, 9369, 3468, 7783, 2199, 8836, 1470, 3823, 8622, 4063, 361, 4500, 5232, 7162, 1883, 2179, 4092, 6209, 8143, 7934, 2745, 7121, 7588, 36, 7428, 8914, 8670, 2621, 2180, 1460, 2956, 2448, 2171, 5771, 8587, 6922, 1745, 3098, 2429, 2990, 1157, 7390, 7576, 8157, 6066, 35, 8273, 9477, 6500, 7455, 6574, 8239, 1417, 5753, 1696, 2551, 4903, 7442, 4738, 8615, 388

In [ ]:
# Day 9
## Part 1

In [225]:
lines = tuple(open('day_9_input.txt', 'r'))

array = [[int(d) for d in line.strip()] for line in lines]

import numpy as np
depth_map = np.array(array)

depth_map_pad = np.hstack((np.ones((depth_map.shape[0],1))*100, depth_map, np.ones((depth_map.shape[0],1))*100))
depth_map_pad = np.vstack((np.ones((1,depth_map.shape[1]+2))*100, depth_map_pad, np.ones((1,depth_map.shape[1]+2))*100))

low_points = dict()
print(depth_map_pad)
for i in range(1,depth_map.shape[0]+1):
    for j in range(1,depth_map.shape[1]+1):
        
#       print(i,j, depth_map_pad[i][j], depth_map_pad[i-1][j], depth_map_pad[i+1][j], depth_map_pad[i][j-1], depth_map_pad[i][j+1])
        
        if depth_map_pad[i][j] < depth_map_pad[i-1][j] and \
        depth_map_pad[i][j] < depth_map_pad[i+1][j] and \
        depth_map_pad[i][j] < depth_map_pad[i][j-1] and \
        depth_map_pad[i][j] < depth_map_pad[i][j+1]:
            low_points["({},{})".format(i,j)] = depth_map_pad[i][j]

#print(low_points)

risk_level = sum([x+1 for x in low_points.values()])
print(risk_level)


[[100. 100. 100. ... 100. 100. 100.]
 [100.   5.   6. ...   5.   6. 100.]
 [100.   4.   3. ...   4.   1. 100.]
 ...
 [100.   0.   2. ...   8.   9. 100.]
 [100.   1.   6. ...   7.   8. 100.]
 [100. 100. 100. ... 100. 100. 100.]]
452.0


In [226]:
##Part 2

In [285]:
lines = tuple(open('day_9_input.txt', 'r'))

array = [[int(d) for d in line.strip()] for line in lines]

import numpy as np
depth_map = np.array(array)

depth_map_pad = np.hstack((np.ones((depth_map.shape[0],1))*100, depth_map, np.ones((depth_map.shape[0],1))*100))
depth_map_pad = np.vstack((np.ones((1,depth_map.shape[1]+2))*100, depth_map_pad, np.ones((1,depth_map.shape[1]+2))*100))

low_points = list()
for i in range(1,depth_map.shape[0]+1):
    for j in range(1,depth_map.shape[1]+1):        
        if depth_map_pad[i][j] < depth_map_pad[i-1][j] and \
        depth_map_pad[i][j] < depth_map_pad[i+1][j] and \
        depth_map_pad[i][j] < depth_map_pad[i][j-1] and \
        depth_map_pad[i][j] < depth_map_pad[i][j+1]:
            low_points.append((i-1,j-1))


#basin_mask = np.where(depth_map == 9)
#basin_map = np.ma.masked_where(basin_mask == False, np.zeros(depth_map.shape))

basin_map = np.where(depth_map == 9,-1,0)

for i,(x,y) in enumerate(low_points):
    basin_map[x][y] = i+1

basin_map_pad = np.hstack((np.ones((basin_map.shape[0],1,))*(-1), basin_map, np.ones((basin_map.shape[0],1,))*(-1)))
basin_map_pad = np.vstack((np.ones((1,basin_map.shape[1]+2,))*(-1), basin_map_pad, np.ones((1,basin_map.shape[1]+2,))*(-1)))

#print(basin_map_pad)

while(0 in basin_map_pad):
    for i in range(1,basin_map_pad.shape[0]-1):
        for j in range(1,basin_map_pad.shape[1]-1):
            
            neighbouring_basin = max(basin_map_pad[i-1][j],
                                    basin_map_pad[i+1][j],
                                    basin_map_pad[i][j-1],
                                    basin_map_pad[i][j+1])
            
            if basin_map_pad[i][j] == 0:
                basin_map_pad[i][j] = neighbouring_basin
#    print(basin_map_pad)

unique, counts = np.unique(basin_map_pad, return_counts=True)
count_dicts = dict(zip(unique, counts))

print(count_dicts)
del count_dicts[-1]
print(count_dicts)

print(sorted(count_dicts.values()))

print(sum(sorted(count_dicts.values())[-4:]))

{-1.0: 2990, 1.0: 2, 2.0: 46, 3.0: 35, 4.0: 4, 5.0: 8, 6.0: 10, 7.0: 49, 8.0: 38, 9.0: 18, 10.0: 33, 11.0: 32, 12.0: 61, 13.0: 30, 14.0: 97, 15.0: 16, 16.0: 6, 17.0: 74, 18.0: 11, 19.0: 36, 20.0: 56, 21.0: 3, 22.0: 2, 23.0: 38, 24.0: 33, 25.0: 39, 26.0: 16, 27.0: 53, 28.0: 66, 29.0: 23, 30.0: 12, 31.0: 26, 32.0: 62, 33.0: 57, 34.0: 14, 35.0: 82, 36.0: 35, 37.0: 7, 38.0: 8, 39.0: 45, 40.0: 13, 41.0: 3, 42.0: 97, 43.0: 66, 44.0: 95, 45.0: 26, 46.0: 74, 47.0: 28, 48.0: 41, 49.0: 9, 50.0: 35, 51.0: 4, 52.0: 22, 53.0: 2, 54.0: 21, 55.0: 18, 56.0: 38, 57.0: 9, 58.0: 46, 59.0: 18, 60.0: 65, 61.0: 11, 62.0: 84, 63.0: 26, 64.0: 38, 65.0: 44, 66.0: 54, 67.0: 16, 68.0: 53, 69.0: 20, 70.0: 71, 71.0: 51, 72.0: 84, 73.0: 10, 74.0: 40, 75.0: 32, 76.0: 7, 77.0: 52, 78.0: 32, 79.0: 31, 80.0: 5, 81.0: 63, 82.0: 26, 83.0: 72, 84.0: 74, 85.0: 87, 86.0: 3, 87.0: 25, 88.0: 56, 89.0: 9, 90.0: 32, 91.0: 82, 92.0: 6, 93.0: 35, 94.0: 28, 95.0: 4, 96.0: 37, 97.0: 3, 98.0: 6, 99.0: 23, 100.0: 61, 101.0: 41, 102.0

In [287]:
# Day 10
## Part 1

In [308]:
lines = tuple(open('day_10_input.txt', 'r'))

In [309]:
points = {')':3,']':57,'}':1197,'>':25137}

score = {')':0,']':0,'}':0,'>':0}

for line in lines:
    still_going = True
    while still_going:
        len_first = len(line)
        line = line.replace('()','')
        line = line.replace('[]','')
        line = line.replace('{}','')
        line = line.replace('<>','')
        if len(line) == len_first:
            still_going = False
        #still_going = False
    indices = {i:line.find(i) for i in ')]}>' if line.find(i) > 0}
    #print(indices)
    #print(min([i for i in indices. if i > 0]))
    if len(indices) > 0 :
        min_index = min(indices, key=indices.get)
        #print(min_index)
        score[min_index] = score[min_index] + 1

print(sum([score[i]*points[i] for i in points.keys()]))

168417


In [ ]:
## Part 2

In [326]:
lines = tuple(open('day_10_input.txt', 'r')) 
points = {')':1,']':2,'}':3,'>':4}

# 3152209039 too high

scores = list()

for line in lines:
    still_going = True
    line = line.strip()
    while still_going:
        len_first = len(line)
        line = line.replace('()','')
        line = line.replace('[]','')
        line = line.replace('{}','')
        line = line.replace('<>','')
        if len(line) == len_first:
            still_going = False
        #still_going = False
    indices = {i:line.find(i) for i in ')]}>' if line.find(i) > 0}
    if len(indices) == 0:
        print(line)
        completion_string = "".join(reversed(line.replace('(',')').replace('[',']').replace('{','}').replace('<','>')))

        score = 0
        for c in completion_string:
            score = score * 5 + points[c]
        scores.append(score)

print(sorted(scores))

print(sorted(scores)[int(len(scores)/2)])

    #print("".join(reversed("".join([chr(ord(c)+1) for c in line]))))
#     indices = {i:line.find(i) for i in ')]}>' if line.find(i) > 0}
    #print(indices)
    #print(min([i for i in indices. if i > 0]))
#     if len(indices) > 0 :
#         min_index = min(indices, key=indices.get)
#         #print(min_index)
#         score[min_index] = score[min_index] + 1

# print(sum([score[i]*points[i] for i in points.keys()]))

(<[<[((<((<{(<[
[[({[{(((<<{{[
<{{{<({[{<{{<(
{[[[((<(<(<[{{
[<{([{<[<<<(
<<<<{[<(<{[{(
<(<({{{<((<<{
{[([{((<({([[
{(<<[{(<<<(<<(
<<<{[(<(<{<{<[
<{(({{{[<(
<[[[<<{[<{{{{
((({(<<({[{[<((
{<{(<[<{[<[(([
([({((([<<([([
[{(<<{((((<<([<
{<[[<{<<(({{((
<[([<(({<{[<[[
((({({[[[{({(
<<<{[<(<({{<{(<
(({[(<<<<{{(<
[<((<{{[(<<{{{(
[(({<<{([[<{[
<[{[<<({<<<[[<
{(((((<({{
(({([{<([{(<[{[
[[{{<([<[<
{({{{{[[[{<[[((
({[((<{{<<(<{<[
([{{({({{{(<{<[
[[[<[([<([((
(({(<({[[([(
({{[<<{<<[([{{
(<({{([{<(<(<
(<{<([[[([{(
{(([<{<(<(
(<((<{[[{([[[[[
{({([[[[[<[[{
[<[([{<{<[{[(<
<([({({{(([({<
[{(({(({<[([[[[
<<{{<[(([{(<(({
({(<({([({({(<
<[{<{((<{(<<[[(
<{[[({[{[{[
(({(<((({{[({([
([(({<([{
[1358286, 3668408, 3730169, 7175783, 8943587, 26447819, 63239312, 71302706, 82616846, 97495222, 407229156, 417727499, 602286538, 678656032, 858398333, 915843439, 969511484, 1062497831, 1068239796, 1643355948, 2382240469, 2412058108, 2762805848, 2802519786, 3152209039, 3367682912, 3611082999, 4507796591, 4534910313, 52596

In [ ]:
# Day 11
## Part 1 & Part 2 (part 1 100 steps only)

In [415]:
import time
lines = tuple(open('day_11_input.txt', 'r'))

array = [[int(d) for d in line.strip()] for line in lines]

array = np.array(array)
total_flashes = 0
for step in range(0,1000):

    all_flashes = np.full(array.shape, False)
    new_flashes = np.full(array.shape, True)

    array = array + 1
    while np.any(new_flashes):
        flashes = array > 9
        new_flashes = np.logical_xor(all_flashes,flashes)
        all_flashes = np.logical_or(all_flashes,flashes)

        new_flash_locs = np.argwhere(new_flashes)

        for i,j in new_flash_locs:
            n_range = range(i-1 if i > 0 else 0,i+2 if i < array.shape[0] - 1 else array.shape[0])
            m_range = range(j-1 if j > 0 else 0,j+2 if j < array.shape[1] - 1 else array.shape[1])
            for n in n_range:
                for m in m_range:
                    array[n][m] = array[n][m]+1
                    

    array = np.where(all_flashes,0,array)
    #print('\n'.join(''.join(str(cell) for cell in row) for row in array))
    #print()
    
    unique, counts = np.unique(array, return_counts=True)
    counts_dict = dict(zip(unique, counts))
    if 0 in counts_dict:
        print(counts_dict[0])
        if counts_dict[0] == 100:
            print(step+1)
            break
    
    
    
    unique, counts = np.unique(flashes, return_counts=True)
    counts_dict = dict(zip(unique, counts))
    #print(counts_dict)
    total_flashes = total_flashes + (counts_dict[True] if True in counts_dict else 0)

print(array)
print(total_flashes)

59
27
13
6
13
25
51
7
5
13
28
1
7
48
17
27
1
4
5
49
17
29
1
1
17
28
16
35
7
15
12
17
57
19
3
6
6
11
17
57
9
3
7
12
24
1
52
9
5
8
25
1
7
51
15
21
12
3
4
56
8
20
3
9
8
17
40
25
8
25
3
2
59
10
13
4
13
1
25
51
6
3
5
17
20
10
43
11
6
18
21
1
4
51
11
9
28
3
13
54
7
15
14
4
7
5
70
4
15
7
3
1
21
60
10
2
6
7
19
5
62
6
5
27
2
15
50
16
19
9
10
6
59
24
3
11
3
3
11
69
6
11
6
4
10
17
58
6
12
3
7
19
4
63
8
11
19
4
5
59
7
6
25
2
1
13
54
11
23
4
6
4
10
57
20
12
9
3
4
71
13
9
2
2
3
35
52
3
5
4
8
34
2
46
9
7
2
37
2
5
48
3
5
42
1
5
4
40
6
45
4
5
43
52
4
1
3
86
6
1
4
3
2
85
6
6
2
1
85
12
2
1
91
6
2
1
2
97
2
1
99
1
100
279
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
4341


In [ ]:
#Day 12
##Part 1

In [528]:
lines = tuple(open('day_12_input.txt', 'r'))

In [529]:
cave_links = dict()

for line in lines:
    matches = re.search('([A-Za-z]+)-([A-Za-z]+)',line.strip())
    start = matches.group(1)
    end = matches.group(2)
    print(start,end)
    
    if start not in cave_links:
        cave_links[start] = [end]
    else:
        cave_links[start].append(end)
        
    if end not in cave_links:
        cave_links[end] = [start]
    else:
        cave_links[end].append(start)

GC zi
end zv
lk ca
lk zi
GC ky
zi ca
end FU
iv FU
lk iv
lk FU
GC end
ca zv
lk GC
GC zv
start iv
zv QQ
ca GC
ca FU
iv ca
start lk
zv FU
start zi


In [465]:
paths = list()

def one_more_step(path, next_point):
    #print(next_point)
    next_step = path.copy()
    next_step.append(next_point)
    if next_point == 'end':
        paths.append(next_step)
    elif not (next_point == next_point.lower() and next_point in path):
        for next_next_point in cave_links[next_point]:
            one_more_step(next_step, next_next_point)
            
for next_point in cave_links['start']:
    one_more_step(['start'],next_point)
    
print(paths)
print(len(paths))

5252


In [530]:
# 151408 too high

import time
paths = list()

def one_more_step_double_small(path, next_point):
    #print(next_point)

    next_step = path.copy()
    next_step.append(next_point)

    counts = [next_step.count(x) for x in set(next_step) if x.lower() == x and next_step.count(x) > 1]
    
    if next_point == 'end':
        paths.append(next_step)
    elif next_point == 'start':
        return
    elif len(counts) <= 1:
        if len(counts) == 1:
            if max(counts) > 2:
                #print(next_step)
                #print(counts)
                
                return
        for next_next_point in cave_links[next_point]:
            one_more_step_double_small(next_step, next_next_point)
            
for next_point in cave_links['start']:
    one_more_step_double_small(['start'],next_point)

#for i in range(0,len(paths)):
    #print(paths[i])
#    time.sleep(1)
print(len(paths))

147784


# Day 13
## Part 1

In [755]:
lines = tuple(open('day_13_input.txt', 'r'))

In [756]:
coords = [x.strip().split(',') for x in lines if ',' in x]


(11, 15)


In [612]:
# 839 too high
# 811 too high

In [757]:
coords = [(int(x), int(y)) for x, y in [coord for coord in coords]]
coord_array = np.array(coords)
#print(coord_array)
#print(coord_array.max())
array = np.zeros((coord_array.transpose()[0].max()+1, coord_array.transpose()[1].max()+1))
                 
print(array.shape)

for x,y in coord_array:
    array[x][y] = 1.0
    
#array = array.transpose()

instructions = [x.strip() for x in lines if 'fold' in x]
print(instructions)
print(array)

for i in instructions:
    print(i, 'y' in i)
    if 'y' in i:
        Sx = int(array.shape[0])
        Sy = int(array.shape[1]/2)

        folded_top = np.zeros((Sx,Sy))
        folded_bottom = np.zeros((Sx,Sy))
        print(folded_top.shape)
        print(folded_bottom.shape)
        print(Sx,Sy)
        print(array.shape)
        
        folded_top[:] = array[:Sx,:Sy]
        # Sy+1 only if fold along number is odd
        folded_bottom[:] = array[:Sx,Sy+1:]
        folded_bottom = np.flip(folded_bottom,axis=1)
        array = np.zeros((Sx,Sy))
        array[:] = folded_top + folded_bottom
    else:
        Sx = int(array.shape[0]/2)
        Sy = int(array.shape[1])

        folded_left = np.zeros((Sx,Sy))
        folded_right = np.zeros((Sx,Sy))

        folded_left[:] = array[:Sx,:Sy]
        folded_right[:] = array[Sx+1:,:Sy]
        folded_right = np.flip(folded_right,axis=0)
        array = np.zeros((Sx,Sy))
        array[:] = folded_left + folded_right

    print(array)
    print(array.shape)
    print(np.count_nonzero(array))

(1311, 895)
['fold along x=655', 'fold along y=447', 'fold along x=327', 'fold along y=223', 'fold along x=163', 'fold along y=111', 'fold along x=81', 'fold along y=55', 'fold along x=40', 'fold along y=27', 'fold along y=13', 'fold along y=6']
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
fold along x=655 False
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(655, 895)
745
fold along y=447 True
(655, 447)
(655, 447)
655 447
(655, 895)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(655, 447)
621
fold along x=327 False
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0.

In [763]:
tarray = array.transpose()
out_str = ""
for i in range(0,tarray.shape[0]):
    for j in range(0,tarray.shape[1]):
        out_str+= '#' if tarray[i][j] != 0 else '.'
    out_str+= '\n'
print(out_str)

.##..###..#..#...##.####.###...##...##..
#..#.#..#.#.#.....#.#....#..#.#..#.#..#.
#..#.###..##......#.###..###..#....#....
####.#..#.#.#.....#.#....#..#.#.##.#....
#..#.#..#.#.#..#..#.#....#..#.#..#.#..#.
#..#.###..#..#..##..#....###...###..##..



In [ ]:
# Day 14
## Part 1

In [837]:
lines = tuple(open('day_14_input.txt', 'r'))

In [838]:
start = lines[0].strip()

rules = [x.split(' -> ') for x in lines if '->' in x]
rules = {x[0]:x[1].strip() for x in rules}


chain = start
for s in range(0,40):
    print(s,len(chain))
    next_chain = ""
    for i in range(0,len(chain)-1):
        next_chain+= chain[i]
        for r, k in rules.items():
            #print(r, k)
            #print(chain[i:i+1])
            if chain[i:i+2] == r:
                #print(r, k)
                #updates[i] = k
                next_chain += k
    next_chain += chain[-1]
    chain = next_chain
    #print(next_chain)

counts = {x:next_chain.count(x) for x in set(next_chain)}
print(counts)

minkey = min(counts, key=counts.get)
maxkey = max(counts, key=counts.get)
print(counts[maxkey]-counts[minkey])


0 20
1 39
2 77
3 153
4 305
5 609
6 1217
7 2433
8 4865
9 9729
10 19457
11 38913
12 77825
13 155649
14 311297
15 622593
16 1245185
17 2490369
18 4980737


KeyboardInterrupt: 

In [ ]:
3523 - 755
# 2517 too low

In [942]:
lines = tuple(open('day_14_input.txt', 'r'))
start = lines[0].strip()

rules = [x.split(' -> ') for x in lines if '->' in x]
rules = {x[0]:x[1].strip() for x in rules}

chain = start
chain_counts = {''.join(x):len(re.findall(''.join(x),chain)) for x in zip(chain, chain[1:])}
print(chain_counts)

for step in range(0, 40):
    next_chain_counts = dict()#chain_counts.copy()
    for ck in chain_counts.keys():
        if ck in rules.keys():
            num_keys_to_replace = chain_counts[ck]
            #next_chain_counts.pop(ck)

            k = rules[ck]

            fk = ck[0]+k
            bk = k+ck[1]
            
            if fk in next_chain_counts:
                next_chain_counts[fk] += num_keys_to_replace
            else:
                next_chain_counts[fk] = num_keys_to_replace
            if bk in next_chain_counts:
                next_chain_counts[bk] += num_keys_to_replace
            else:
                next_chain_counts[bk] = num_keys_to_replace
        else:
            next_chain_counts[ck] = chain_counts[ck]
    chain_counts = next_chain_counts.copy()
                
    print(chain_counts)

{'OF': 1, 'FS': 1, 'SN': 2, 'NK': 2, 'KK': 1, 'KH': 1, 'HC': 1, 'CB': 1, 'BS': 1, 'KB': 1, 'BK': 1, 'KF': 1, 'FF': 1, 'FC': 1, 'CV': 1, 'VN': 1, 'NB': 1}
{'OV': 1, 'VF': 1, 'FK': 1, 'KS': 2, 'SV': 2, 'VN': 2, 'NO': 2, 'OK': 2, 'KB': 2, 'BK': 2, 'KH': 1, 'HH': 1, 'HP': 1, 'PC': 1, 'CH': 1, 'HB': 1, 'BV': 1, 'VS': 1, 'BB': 2, 'SF': 1, 'FH': 1, 'HF': 1, 'FB': 2, 'BC': 1, 'CF': 1, 'FV': 1, 'VO': 1, 'ON': 1, 'NF': 1}
{'OK': 1, 'KV': 1, 'VC': 1, 'CF': 2, 'FN': 2, 'NK': 1, 'KN': 2, 'NS': 2, 'SO': 2, 'OV': 2, 'VO': 3, 'ON': 3, 'NF': 2, 'FO': 2, 'OF': 2, 'FK': 3, 'KB': 2, 'BB': 4, 'BK': 2, 'KH': 2, 'HH': 3, 'HB': 3, 'BH': 2, 'BP': 3, 'PS': 1, 'SC': 1, 'CH': 1, 'HV': 2, 'VF': 3, 'FS': 3, 'PB': 2, 'SV': 1, 'SB': 2, 'BF': 1, 'FC': 1, 'FF': 1, 'NV': 1, 'VV': 1, 'NN': 1, 'NH': 1, 'HF': 1}
{'OF': 1, 'FK': 4, 'KB': 5, 'BV': 2, 'VS': 4, 'SC': 1, 'CF': 5, 'FF': 2, 'FV': 2, 'VN': 2, 'NO': 1, 'OK': 3, 'KC': 3, 'CN': 2, 'NV': 2, 'SP': 2, 'PO': 2, 'KV': 3, 'VV': 5, 'VO': 3, 'ON': 3, 'NN': 3, 'NH': 2, 'HF': 

In [943]:
for c in set(''.join(chain_counts.keys())):
    final_sum = sum([v for k,v in chain_counts.items() if k[0] == c])
    if c == start[-1] == c:
        final_sum+=1
    print(c,final_sum)
    


K 1157575573379
N 2396290071858
S 1065735169668
H 2599818937857
C 784693342291
P 2621384155556
V 2156262136828
O 1758917431802
B 3699058479790
F 2650985628716


In [945]:
final_char_counts = dict()
for c in set(''.join(chain_counts.keys())):
    final_sum = sum([v for k,v in chain_counts.items() if k[0] == c])
    if c == start[-1]:
        final_sum+=1
    final_char_counts[c] = final_sum

minkey = min(final_char_counts, key=final_char_counts.get)
maxkey = max(final_char_counts, key=final_char_counts.get)

print(chain)
print(minkey,maxkey)

print(final_char_counts[maxkey]-final_char_counts[minkey])

# 1223373208545 too low
# 2610798035609 too low

OFSNKKHCBSNKBKFFCVNB
C B
2914365137499


In [873]:
# Day 15
## Part 1

B
3
2


In [956]:
df = pd.read_csv("day_15_test_input.txt",header=None)
df[0] = df[0].astype(str)
#df[0] = df[0].apply(lambda x: x.strip())
df = df[0].apply(lambda x: pd.Series(list(x)))

print(df)

   0  1  2  3  4  5  6  7  8  9
0  1  1  6  3  7  5  1  7  4  2
1  1  3  8  1  3  7  3  6  7  2
2  2  1  3  6  5  1  1  3  2  8
3  3  6  9  4  9  3  1  5  6  9
4  7  4  6  3  4  1  7  1  1  1
5  1  3  1  9  1  2  8  1  3  7
6  1  3  5  9  9  1  2  4  2  1
7  3  1  2  5  4  2  1  6  3  9
8  1  2  9  3  1  3  8  5  2  1
9  2  3  1  1  9  4  4  5  8  1


In [980]:
from scipy.sparse import csr_matrix
from scipy.sparse.csgraph import shortest_path

# distance from (x1,y2) to (x2,y2) is 0 
# unless abs(x1-x2) = 1 or abs(y1-y2) = 1
# and (x2,y2) otherwise

df = pd.DataFrame([[1,1,6,3],
                   [1,3,8,1],
                   [2,1,3,6],
                   [3,6,9,4]])

# 10 x 10 list of locations. graph array size is 100 x 100
graph = np.zeros((df.shape[0]*df.shape[1],df.shape[0]*df.shape[1]))
#print(graph)
for i in range(0,df.shape[0]):
    for j in range(0,df.shape[1]):
        if not i == 0:
            graph[i-1][j] = df[i][j]
        #if not i == 
        graph[i+1][j] = df[i][j]
        if not j == 0:
            graph[i][j-1] = df[i][j]
        graph[i][j+1] = df[i][j]

print(graph)
        
graph = csr_matrix(graph)
#print(graph)
dist_matrix, predecessors = shortest_path(csgraph=graph, directed=False, indices=0, return_predecessors=True)
print(dist_matrix)
print(predecessors)

[[1. 3. 1. 6. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [6. 8. 3. 9. 6. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [3. 1. 6. 4. 9. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 6. 4. 6. 4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [3. 1. 6. 4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[ 0.  2.  1.  1.  3. inf inf inf inf inf inf inf inf inf inf inf]
[-9999     2     0     0     0 -9999 -9999 -9999 -9999 -9999 -9999 -9999
 -9999 -9999 -9999 -9999]


In [1042]:
import networkx as nx
df = pd.read_csv("day_15_input.txt",header=None)
df[0] = df[0].astype(str)
#df[0] = df[0].apply(lambda x: x.strip())
df = df[0].apply(lambda x: pd.Series([int(n) for n in list(x)]))


# pad = df

# pad = np.hstack((np.ones((depth_map.shape[0],1))*1000, pad, np.ones((depth_map.shape[0],1))*1000))
# pad = np.vstack((np.ones((1,depth_map.shape[1]+2))*1000, pad, np.ones((1,depth_map.shape[1]+2))*1000))

# df = pad

G = nx.DiGraph()
num_edges = 0
for i in range(0,df.shape[0]):
    for j in range(0,df.shape[1]):
        #G.add_node("{}{}".format(i,j))
        if i > 0:
            G.add_edge("{}.{}".format(i,j),"{}.{}".format(i-1,j),weight=df[i][j])
        if i < df.shape[0] - 1:
            G.add_edge("{}.{}".format(i,j),"{}.{}".format(i+1,j),weight=df[i][j])
        if j > 0:
            G.add_edge("{}.{}".format(i,j),"{}.{}".format(i,j-1),weight=df[i][j])
        if j < df.shape[1] - 1:
            G.add_edge("{}.{}".format(i,j),"{}.{}".format(i,j+1),weight=df[i][j])
print(G)
            
print(num_edges)
source = "0.0"
target = "{}.{}".format(df.shape[0]-1,df.shape[1]-1)
path = nx.shortest_path(G,source=source,target=target,weight='weight',method='bellman-ford')
cost = nx.shortest_path_length(G,source=source,target=target,weight='weight',method='bellman-ford')

print(path)
print(cost)

DiGraph with 10000 nodes and 39600 edges
0
['0.0', '1.0', '2.0', '2.1', '2.2', '2.3', '2.4', '3.4', '3.5', '3.6', '3.7', '2.7', '2.8', '2.9', '3.9', '3.10', '3.11', '3.12', '3.13', '3.14', '4.14', '4.15', '4.16', '4.17', '4.18', '5.18', '5.19', '5.20', '5.21', '6.21', '7.21', '7.22', '7.23', '7.24', '7.25', '8.25', '9.25', '10.25', '10.26', '10.27', '10.28', '10.29', '11.29', '11.30', '12.30', '12.31', '12.32', '13.32', '14.32', '15.32', '16.32', '17.32', '17.33', '17.34', '17.35', '18.35', '18.36', '19.36', '20.36', '20.37', '21.37', '22.37', '22.38', '22.39', '22.40', '22.41', '23.41', '24.41', '25.41', '25.42', '25.43', '26.43', '26.44', '26.45', '27.45', '27.46', '28.46', '29.46', '29.47', '30.47', '30.48', '30.49', '31.49', '32.49', '33.49', '34.49', '35.49', '36.49', '37.49', '37.50', '37.51', '38.51', '38.52', '38.53', '38.54', '38.55', '39.55', '39.56', '39.57', '39.58', '40.58', '40.59', '40.60', '40.61', '41.61', '42.61', '42.62', '42.63', '42.64', '43.64', '43.65', '43.66', 

In [1046]:
# 491 too low

ct = 0
for i in path[1:]:
    loc = i.split('.')
    c1 = df[int(loc[0])][int(loc[1])]
    ct += c1
    print(i,c1,ct)
print(ct)

1.0 1 1
2.0 2 3
2.1 3 6
2.2 2 8
2.3 9 17
2.4 3 20
3.4 1 21
3.5 6 27
3.6 2 29
3.7 2 31
2.7 1 32
2.8 3 35
2.9 1 36
3.9 2 38
3.10 4 42
3.11 3 45
3.12 2 47
3.13 3 50
3.14 2 52
4.14 1 53
4.15 1 54
4.16 5 59
4.17 1 60
4.18 2 62
5.18 6 68
5.19 4 72
5.20 3 75
5.21 3 78
6.21 1 79
7.21 2 81
7.22 1 82
7.23 1 83
7.24 1 84
7.25 2 86
8.25 2 88
9.25 1 89
10.25 5 94
10.26 2 96
10.27 1 97
10.28 1 98
10.29 2 100
11.29 1 101
11.30 4 105
12.30 5 110
12.31 5 115
12.32 1 116
13.32 3 119
14.32 1 120
15.32 2 122
16.32 1 123
17.32 2 125
17.33 1 126
17.34 1 127
17.35 2 129
18.35 1 130
18.36 6 136
19.36 1 137
20.36 7 144
20.37 1 145
21.37 1 146
22.37 1 147
22.38 4 151
22.39 1 152
22.40 9 161
22.41 2 163
23.41 7 170
24.41 1 171
25.41 1 172
25.42 1 173
25.43 1 174
26.43 2 176
26.44 3 179
26.45 2 181
27.45 1 182
27.46 1 183
28.46 8 191
29.46 1 192
29.47 2 194
30.47 4 198
30.48 3 201
30.49 3 204
31.49 1 205
32.49 2 207
33.49 2 209
34.49 5 214
35.49 2 216
36.49 1 217
37.49 4 221
37.50 3 224
37.51 1 225
38.51 1 226
38

In [1047]:

## Part 2

In [1101]:
import networkx as nx
df = pd.read_csv("day_15_input.txt",header=None)
df[0] = df[0].astype(str)
#df[0] = df[0].apply(lambda x: x.strip())
df = df[0].apply(lambda x: pd.Series([int(n) for n in list(x)]))


G = nx.DiGraph()
num_edges = 0
for r in range(0,5):
    for s in range(0,5):
        for i in range(0,df.shape[0]):
            for j in range(0,df.shape[1]):
                #G.add_node("{}{}".format(i,j))
                this_weight = df[i][j]+r+s
                src_i = r*df.shape[0]+i
                src_j = s*df.shape[1]+j
                if(src_i == 49 and src_j == 49):
                    print(this_weight)
                if this_weight > 9:
                    this_weight -= 9
                if src_i > 0:
                    G.add_edge("{}.{}".format(src_i-1,src_j),"{}.{}".format(src_i,src_j),weight=this_weight)
                if i < 5*df.shape[0] - 1:
                    G.add_edge("{}.{}".format(src_i+1,src_j),"{}.{}".format(src_i,src_j),weight=this_weight)
                if src_j > 0:
                    G.add_edge("{}.{}".format(src_i,src_j-1),"{}.{}".format(src_i,src_j),weight=this_weight)
                if j < 5*df.shape[1] - 1:
                    G.add_edge("{}.{}".format(src_i,src_j+1),"{}.{}".format(src_i,src_j),weight=this_weight)

source = "0.0"
target = "{}.{}".format(df.shape[0]*5-1,df.shape[1]*5-1)
path = nx.shortest_path(G,source=source,target=target,weight='weight')


9


In [1102]:
ct = 0
for i in range(0,len(path)-1):
    c1 = G.get_edge_data(path[i],path[i+1])['weight']
    ct += c1
    print(path[i],path[i+1], c1, ct)
print(G.get_edge_data("48.49","49.49")['weight'])

0.0 1.0 1 1
1.0 2.0 2 3
2.0 3.0 3 6
3.0 4.0 1 7
4.0 4.1 8 15
4.1 4.2 3 18
4.2 4.3 2 20
4.3 4.4 2 22
4.4 4.5 3 25
4.5 4.6 8 33
4.6 5.6 2 35
5.6 5.7 1 36
5.7 5.8 2 38
5.8 6.8 2 40
6.8 7.8 3 43
7.8 8.8 1 44
8.8 9.8 4 48
9.8 9.9 1 49
9.9 9.10 1 50
9.10 10.10 9 59
10.10 11.10 2 61
11.10 12.10 5 66
12.10 13.10 4 70
13.10 14.10 2 72
14.10 15.10 1 73
15.10 16.10 2 75
16.10 17.10 1 76
17.10 18.10 6 82
18.10 19.10 6 88
19.10 20.10 2 90
20.10 21.10 1 91
21.10 21.9 1 92
21.9 22.9 4 96
22.9 23.9 4 100
23.9 24.9 1 101
24.9 25.9 1 102
25.9 26.9 4 106
26.9 27.9 1 107
27.9 28.9 1 108
28.9 29.9 9 117
29.9 30.9 4 121
30.9 31.9 2 123
31.9 32.9 1 124
32.9 32.10 1 125
32.10 32.11 2 127
32.11 33.11 2 129
33.11 34.11 3 132
34.11 35.11 1 133
35.11 36.11 1 134
36.11 36.12 2 136
36.12 36.13 4 140
36.13 36.14 3 143
36.14 37.14 3 146
37.14 38.14 2 148
38.14 38.15 4 152
38.15 38.16 1 153
38.16 39.16 5 158
39.16 39.17 2 160
39.17 40.17 1 161
40.17 40.18 4 165
40.18 40.19 1 166
40.19 41.19 5 171
41.19 42.19 1 172
42.

398.333 398.334 4 1999
398.334 398.335 2 2001
398.335 399.335 1 2002
399.335 399.336 4 2006
399.336 400.336 1 2007
400.336 400.337 2 2009
400.337 400.338 2 2011
400.338 400.339 8 2019
400.339 400.340 6 2025
400.340 400.341 7 2032
400.341 400.342 1 2033
400.342 400.343 7 2040
400.343 400.344 1 2041
400.344 400.345 4 2045
400.345 400.346 2 2047
400.346 401.346 5 2052
401.346 401.347 2 2054
401.347 402.347 2 2056
402.347 402.348 2 2058
402.348 402.349 2 2060
402.349 403.349 3 2063
403.349 404.349 2 2065
404.349 405.349 4 2069
405.349 405.350 2 2071
405.350 405.351 2 2073
405.351 406.351 3 2076
406.351 407.351 7 2083
407.351 407.352 2 2085
407.352 408.352 1 2086
408.352 409.352 1 2087
409.352 410.352 4 2091
410.352 411.352 2 2093
411.352 412.352 1 2094
412.352 412.353 6 2100
412.353 412.354 3 2103
412.354 413.354 1 2104
413.354 414.354 7 2111
414.354 415.354 1 2112
415.354 415.355 2 2114
415.355 415.356 3 2117
415.356 415.357 1 2118
415.357 415.358 7 2125
415.358 415.359 1 2126
415.359 416

In [2]:
# 1767 too low
# 2136 too low

In [3]:
# Day 16
## Part 2

In [216]:
bits = tuple(open('day_16_input.txt', 'r'))[0].strip()

#bits = '620080001611562C8802118E34'

i = int(bits, 16)
bin_str = "{0:b}".format(i)
bin_str = "".join(['0']*(len(bits)*4-len(bin_str))) + bin_str
print(len(bin_str))

versions = list()

def parse_packet(bin_str):#, len_subpackets=None, num_subpackets=None):
#     if bin_str == '':
#         return 0
#     full_bin_string = int(bin_str,2)
#     if full_bin_string == 0:
#         print(full_bin_string)
#         return len(bin_str)
    
    #if(len(bin_str) < 11):
    #    print(bin_str)
    #    return len(bin_str)
    
    print("bin_str", bin_str)
    #print("len_bin_str", len(bin_str))
    version = int(bin_str[0:3],2)
    versions.append(version)
    #print("version",version)
    type_id = int(bin_str[3:6],2)
    print("TYPEID",type_id)

    if type_id == 4:
        bin_str_chunks = [bin_str[5*x+6:5*x+6+5] for x in range(0,int((len(bin_str)-6)/5))]
        bin_str_chunks = bin_str_chunks[0:1+[i for i,x in enumerate(bin_str_chunks) if x.startswith('0')][0]]
        literal = "".join([x[1:] for x in bin_str_chunks])
        literal_dec = int(literal,2)
        print("LITERAL {}".format(literal_dec))
        this_packet_length = 6 + len(bin_str_chunks)*5
        #print("THIS PACK", this_packet_length)
        
        rem = len(bin_str) - this_packet_length
        #if rem > 11:
        return this_packet_length
        #else:
        #    print("ERLERJK:EKR:KER")
        #    return rem
    else:
        print("OPERATOR")
        length_type_id = bin_str[6]
        #print("length_type_id",length_type_id)
        if length_type_id == '0':
            total_length_sub_packets = int(bin_str[7:22],2)
            print("total_length_sub_packets", total_length_sub_packets)
            parsed = 0
            for i in range(0,10):
                if parsed < total_length_sub_packets:
                    one_packet = parse_packet(bin_str[22+parsed:])
                    parsed = parsed + one_packet
                    print("parsed",parsed, total_length_sub_packets)
            return parsed + 22
        else:
            num_sub_packets = int(bin_str[7:18],2)
            parsed = 0
            for i in range(0, num_sub_packets):
                one_packet = parse_packet(bin_str[18+parsed:])
                parsed = parsed + one_packet            
            return parsed + 18


parse_packet(bin_str)

print(versions)
print(sum(versions))

5472
bin_str 101000100000110101011100111011001011110101101100000001100001000000000110111001111000000000010010001001001010111100100101000110101110101000000110110100100011000110011001000001001001001000011000100000000001000100111010100100110001101000010100000000101010100111011000001111010100001111001001111111111100110000011110010101101111111100101001100010010000111000000000110001000010100110000100001100110111101111110010001011000101000000100000000010001100001001101001100000101000000000010000000010010100001001101001001101110011001000000001001001001110011000000010101111000000000100011001001011110100101001110100111111010111101101110000011010010010111101001010011101001111110101111011011100000000010000000011000101110000010000000000111101110000000000101101110000000000111001110000000000111100010000000000101100000000001000110111000000000000100000101100011000000001110111111000110000000000110100110000000000111000000000000101101010100000000000010011111101000000000001000100111001110000000000101101010

In [18]:
from numpy import prod
bits = tuple(open('day_16_input.txt', 'r'))[0].strip()

#bits = '9C0141080250320F1802104A08'

i = int(bits, 16)
bin_str = "{0:b}".format(i)
bin_str = "".join(['0']*(len(bits)*4-len(bin_str))) + bin_str
print(len(bin_str))

versions = list()

def calc(type_id, literals):
    match type_id:
        case 0:
            # sum
            out = sum(literals)
            print("SUM", out)
            return out
        case 1:
            # prduct
            out = prod(literals)
            print("PROD", out)
            return out
        case 2:
            # min
            out = min(literals)
            print("MIN", out)
            return out
        case 3:
            # max
            out = max(literals)
            print("MAX", out)
            return out
        case 5:
            # gt
            if literals[0] > literals[1]:
                print("{} > {}".format(literals[0], literals[1]))
                return 1
            else:
                print("{} <= {}".format(literals[0], literals[1]))
                return 0
        case 6:
            # lt
            if literals[0] < literals[1]:
                print("{} < {}".format(literals[0], literals[1]))
                return 1
            else:
                print("{} >= {}".format(literals[0], literals[1]))
                return 0
        case 7:
            # eq
            if literals[0] == literals[1]:
                print("{} == {}".format(literals[0], literals[1]))
                return 1
            else:
                print("{} != {}".format(literals[0], literals[1]))
                return 0
def parse_packet(bin_str):#, len_subpackets=None, num_subpackets=None):

    print("bin_str", bin_str)
    version = int(bin_str[0:3],2)
    versions.append(version)
    type_id = int(bin_str[3:6],2)
    print("TYPEID",type_id)

    if type_id == 4:
        bin_str_chunks = [bin_str[5*x+6:5*x+6+5] for x in range(0,int((len(bin_str)-6)/5))]
        bin_str_chunks = bin_str_chunks[0:1+[i for i,x in enumerate(bin_str_chunks) if x.startswith('0')][0]]
        literal = "".join([x[1:] for x in bin_str_chunks])
        literal_dec = int(literal,2)
        print("LITERAL {}".format(literal_dec))
        this_packet_length = 6 + len(bin_str_chunks)*5

        rem = len(bin_str) - this_packet_length
        return this_packet_length, literal_dec
    else:
        print("OPERATOR")
 
        length_type_id = bin_str[6]
        if length_type_id == '0':
            total_length_sub_packets = int(bin_str[7:22],2)
            print("total_length_sub_packets", total_length_sub_packets)
            parsed = 0
            literals = list()
            # TODO: This is a hack to prevent infinite loops
            for i in range(0,10):
                if parsed < total_length_sub_packets:
                    one_packet, literal = parse_packet(bin_str[22+parsed:])
                    literals.append(literal)
                    parsed = parsed + one_packet
                    print("parsed",parsed, total_length_sub_packets)
            resolved = calc(type_id, literals)
                
            return parsed + 22, resolved
        else:
            num_sub_packets = int(bin_str[7:18],2)
            parsed = 0
            literals = list()
            for i in range(0, num_sub_packets):
                one_packet, literal = parse_packet(bin_str[18+parsed:])
                literals.append(literal)
                parsed = parsed + one_packet
                # TODO this needs python >= 3.10
            resolved = calc(type_id, literals)

            return parsed + 18, resolved


parse_packet(bin_str)

print(versions)
print(sum(versions))

5472
bin_str 101000100000110101011100111011001011110101101100000001100001000000000110111001111000000000010010001001001010111100100101000110101110101000000110110100100011000110011001000001001001001000011000100000000001000100111010100100110001101000010100000000101010100111011000001111010100001111001001111111111100110000011110010101101111111100101001100010010000111000000000110001000010100110000100001100110111101111110010001011000101000000100000000010001100001001101001100000101000000000010000000010010100001001101001001101110011001000000001001001001110011000000010101111000000000100011001001011110100101001110100111111010111101101110000011010010010111101001010011101001111110101111011011100000000010000000011000101110000010000000000111101110000000000101101110000000000111001110000000000111100010000000000101100000000001000110111000000000000100000101100011000000001110111111000110000000000110100110000000000111000000000000101101010100000000000010011111101000000000001000100111001110000000000101101010

In [1]:
# Day 17
## Parts 1 & 2

In [22]:
import re
input_str = 'target area: x=20..30, y=-10..-5'

input_str = tuple(open('day_17_input.txt', 'r'))[0].strip()

pattern = 'target area: x=(-?\d+)..(-?\d+), y=(-?\d+)..(-?\d+)'

m = re.search(pattern,input_str)
x_min = int(m.group(1))
x_max = int(m.group(2))
y_min = int(m.group(3))
y_max = int(m.group(4))

print(x_min, x_max, y_min, y_max)


def test_shot(x_vel, y_vel, debug = False):
    x_pos = 0
    y_pos = 0
    
    shot_y_max = 0

    for s in range(0, 1000):
        x_pos+=x_vel
        y_pos+=y_vel
        if x_vel > 0:
            x_vel-=1
        elif x_vel == 0:
            pass
        else:
            x_vel+=1
        y_vel-=1
        
        if y_pos > shot_y_max:
            shot_y_max = y_pos
        if debug:
            print(x_pos, y_pos)
        if x_pos in range(x_min, x_max+1) and y_pos in range(y_min, y_max+1):
            if debug:
                print(x_pos in range(x_min, x_max+1))
                print(y_pos in range(y_min, y_max+1))
                print([i for i in range(y_min, y_max +1)])
                print(x_pos in range(x_min, x_max+1) and y_pos in range(y_min, y_max+1))
                print('bullseye')
                print('steps',s)
            return True, shot_y_max
        if x_vel == 0 and x_pos < x_min:
            if debug:
                print('too short')
            return False, -1
        if y_vel < 0 and y_pos < y_min:
            if debug:
                print('overshot')
            return False, -1
        
    return False, -1

print(test_shot(6,0, True))
        
        
tests_y_max = 0

successes = list()
for x_test in range(0, x_max+1):
    for y_test in range(-300,300):
        test, this_y_max = test_shot(x_test, y_test)
        if test:
            successes.append((x_test,y_test))
            #print("success", test, x_test, y_test, this_y_max)
            if this_y_max > tests_y_max:
                tests_y_max = this_y_max

                
for x in successes   :
#    print("{}, {}".format(x[0],x[1]))
    pass
print(len(successes))
# 595 too low

# 3239 too low for successes

FileNotFoundError: [Errno 2] No such file or directory: 'day_17_input.txt'

In [23]:
# Day 18
# Part 1

In [24]:
import re
import math
def explode(test_explode_str):
    d = 0
    for i, c in enumerate(test_explode_str):
        if c == '[':
            d+=1
        if c ==  ']':
            d-=1
        if d == 5:
            #print(test_explode_str[i+1:])
            lookahead = re.search('(\d+),(\d+)', test_explode_str[i:])
            left = lookahead.group(1)
            right = lookahead.group(2)
            #print(left, right)
            
            # explode right?
            search_from = i + lookahead.span()[1]
            #print(test_explode_str[search_from:])
            
            lookright = re.search('(\d+)', test_explode_str[search_from:])
            out_right = test_explode_str[search_from+1:]
            if not lookright is None:
                update_right = str(int(right) + int(lookright.group(1)))
                out_right = out_right.replace(lookright.group(1),update_right,1)
                #print("explode right", out_right)
        
            # explode left?
            out_left = test_explode_str[:i]
            out_left_backwards = ''.join(reversed(out_left))
            lookleft = re.search('(\d+)', out_left_backwards)
            #print(lookleft)
            if not lookleft is None:
                update_left = ''.join(reversed(str(int(left) + int(''.join(reversed(lookleft.group(1)))))))
                out_left = ''.join(reversed(out_left_backwards.replace(lookleft.group(1),update_left,1)))
                #print("explode left")

            explode_out = out_left + '0' + out_right
            #print("explode", explode_out)
            return explode_out, True
            
    return test_explode_str, False



#explode('[[[[4,0],[5,4]],[[7,0],[15,5]]],[10,[[0,[11,3]],[[6,3],[8,8]]]]]')

In [25]:
def split(test_split_str):
    for i, c in enumerate(test_split_str):
        lookahead = re.search('(\d\d+)', test_split_str[i:])
        if not lookahead is None:
            found = lookahead.group(1)
            split_out = test_split_str[:i] + test_split_str[i:].replace(found,"[{},{}]".format(math.floor(int(found)/2), math.ceil(int(found)/2)),1)
            #print("split  ", split_out)
            return split_out, True

    return test_split_str, False

#sf_add('[[[[4,3],4],4],[7,[[8,4],9]]]','[1,1]')

sf_add('[[[[6,6],[6,6]],[[6,0],[6,7]]],[[[7,7],[8,9]],[8,[8,1]]]]','[2,9]')

NameError: name 'sf_add' is not defined

In [26]:
def reduce(test_reduce_str):
    reduced_str, exploded = explode(test_reduce_str)
    if exploded:
        return reduce(reduced_str)
    
    reduced_str, splitted = split(test_reduce_str)
    if splitted:
        return reduce(reduced_str)

    return test_reduce_str

def sf_add(num_a, num_b):
    added = "[{},{}]".format(num_a,num_b)
    #print("added",added)
    reduced_str = reduce(added)
    #print(reduced_str)
    return reduced_str

mag_pattern = '\[(.*),(.*)\]'
    
def magnitude(test_mag_str):
    try:
        return int(test_mag_str)
    except:
        pass
    return 3*magnitude(test_mag_str[0]) + 2* magnitude(test_mag_str[1])


In [27]:
nums = [x.strip() for x in tuple(open('day_18_input.txt', 'r'))]

sf_add(nums[0],nums[1])

running_sum = nums[0]
for i, num in enumerate(nums[1:]):
    #print("  " + running_sum)
    #print("+ " + num)
    running_sum = sf_add(running_sum, num)
    #print("= " + running_sum)
    #print()

# running_sum = reduce(running_sum)
print(running_sum)

import json
j_out = json.loads(running_sum)

print(running_sum)

magnitude(j_out)

[[[[7,7],[7,7]],[[9,5],[8,7]]],[[[6,8],[6,8]],[[6,6],[0,6]]]]
[[[[7,7],[7,7]],[[9,5],[8,7]]],[[[6,8],[6,8]],[[6,6],[0,6]]]]


4173

In [28]:
## Part 2

In [29]:

max_mag = 0
for i in range(0,len(nums)):
    for j in range(0, len(nums)):
        if i != j:
            this_sum = sf_add(nums[i],nums[j])
            mm1 = magnitude(json.loads(this_sum))
            if mm1 > max_mag:
                max_mag = mm1
            this_sum = sf_add(nums[j],nums[i])
            mm1 = magnitude(json.loads(this_sum))
            if mm1 > max_mag:
                max_mag = mm1

In [30]:
print(max_mag)

4706


In [20]:
# Day 19
## Part 1

In [50]:
import pprint
scanner_inputs = [x.strip() for x in tuple(open('day_19_test_input.txt', 'r'))]

scanners = list()
for l in scanner_inputs:
    if 'scanner' in l:
        scanner_l = list()#dict()
        #scanners[l] = scanner_l
        scanners.append(scanner_l)
        i = 1
    elif ',' in l:
        beacon_coords = np.array([int(x) for x in l.split(',')])
        #scanner_l['beacon {}'.format(i)] = dict()
        #scanner_l['beacon {}'.format(i)]['coords'] 
        scanner_l.append(beacon_coords)
        i+=1
    else:
        pass

#pprint.pprint(scanners)
print(scanners[4])

[array([727, 592, 562]), array([-293, -554,  779]), array([ 441,  611, -461]), array([-714,  465, -776]), array([-743,  427, -804]), array([-660, -479, -426]), array([ 832, -632,  460]), array([ 927, -485, -438]), array([ 408,  393, -506]), array([ 466,  436, -512]), array([110,  16, 151]), array([-258, -428,  682]), array([-393,  719,  612]), array([-211, -452,  876]), array([ 808, -476, -593]), array([-575,  615,  604]), array([-485,  667,  467]), array([-680,  325, -822]), array([-627, -443, -432]), array([ 872, -547, -609]), array([833, 512, 582]), array([807, 604, 487]), array([ 839, -516,  451]), array([ 891, -625,  532]), array([-652, -548, -490]), array([ 30, -46, -14])]


In [80]:
import itertools
import pandas as pd
import numpy as np

distance_dfs = list()
for scanner in scanners:
    distance_df = np.zeros((len(scanner),len(scanner)))
    distance_dfs.append(distance_df)
    #beacon_pairs = list(itertools.combinations(scanner,2))
    beacon_pairs = list((i,j) for ((i,_),(j,_)) in itertools.combinations(enumerate(scanner), 2))
    #print(len(beacon_pairs))
    for beacon_1_i, beacon_2_i in beacon_pairs:
        beacon_1 = scanner[beacon_1_i]
        beacon_2 = scanner[beacon_2_i]
        #print(beacon_1, beacon_2)
        distance = np.linalg.norm(beacon_1 - beacon_2)
        distance_df[beacon_1_i][beacon_2_i] = distance
    
#print(distance_dfs)

counts = np.zeros(distance_dfs[0].shape)
for search_x in range(0, len(distance_dfs[0])):
    for search_y in range(search_x+1,len(distance_dfs[0][search_x])):
        search_distance = distance_dfs[0][search_x][search_y]
        search_df = distance_dfs[1]

        sel = np.where(search_df == search_distance)
        if len(sel[0]) == 1 and len((sel[1]) == 1):
            #print("distance scanner_1 from {} to {} matches distance scanner_2 from {} to {}".format(search_x, search_y, sel[0], sel[1]))
            counts[search_x][sel[0]]+=1
            counts[search_y][sel[1]]+=1
            

for r in counts:
    max_this_row = max(r)
    if max_this_row > 0:
        print(max_this_row, np.argwhere(r == max_this_row))

8.0 [[3]]
7.0 [[8]]
6.0 [[12]]
7.0 [[1]]
4.0 [[24]]
5.0 [[18]]
5.0 [[10]]
4.0 [[0]]
5.0 [[2]]
6.0 [[5]]
9.0 [[15]]
10.0 [[19]]
